name: PR auto merge
on:
  schedule:
    - cron: '0 0 * * 1' # 매주 월요일 0시(UTC) -> 매주 화요일 오전 9시(KST) 9시간 시차존재
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          MERGE_LABELS: ""
